version: '3'
services:
  mysql-db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: clique
      MYSQL_PASSWORD: thama
    ports:
      - 3300:3306
    expose:
      - 3306



